//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralKnowledgeBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneralKnowledgeBot.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what I found: {0}.
        /// </summary>
        public static string AnswerLineText {
            get {
                return ResourceManager.GetString("AnswerLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an expert.
        /// </summary>
        public static string AskAnExpertCarouselButtonText {
            get {
                return ResourceManager.GetString("AskAnExpertCarouselButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If my answer isn&apos;t satisfactory, just let me know. I will connect you with our very capable experts!.
        /// </summary>
        public static string AskAnExpertCarouselContent {
            get {
                return ResourceManager.GetString("AskAnExpertCarouselContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an expert.
        /// </summary>
        public static string AskAnExpertCarouselTitle {
            get {
                return ResourceManager.GetString("AskAnExpertCarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        public static string AskAQuestionCarouselButtonText {
            get {
                return ResourceManager.GetString("AskAQuestionCarouselButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        public static string AskAQuestionCarouselCardTitle {
            get {
                return ResourceManager.GetString("AskAQuestionCarouselCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask me a question by typing in the chat box below and I&apos;ll tell you what I know about it....
        /// </summary>
        public static string AskAQuestionCarouselContent {
            get {
                return ResourceManager.GetString("AskAQuestionCarouselContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How relevant are the search results that were returned by the bot?.
        /// </summary>
        public static string FeedbackQuestionText {
            get {
                return ResourceManager.GetString("FeedbackQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give feedback.
        /// </summary>
        public static string GiveFeedbackButtonText {
            get {
                return ResourceManager.GetString("GiveFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❓: {0}.
        /// </summary>
        public static string QuestionLineText {
            get {
                return ResourceManager.GetString("QuestionLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo! 🍀.
        /// </summary>
        public static string ResponseCardTitleText {
            get {
                return ResourceManager.GetString("ResponseCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking the time to share feedback with both the SMEs and my creators. It is prudent that my tiny 🤖🧠 performs better..
        /// </summary>
        public static string ShareAppFeedbackAdaptiveCardContent {
            get {
                return ResourceManager.GetString("ShareAppFeedbackAdaptiveCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App Feedback.
        /// </summary>
        public static string ShareAppFeedbackAdaptiveCardTitle {
            get {
                return ResourceManager.GetString("ShareAppFeedbackAdaptiveCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app feedback.
        /// </summary>
        public static string ShareAppFeedbackCarouselButtonText {
            get {
                return ResourceManager.GetString("ShareAppFeedbackCarouselButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help me become better! Please share feedback on how I am doing so that my expert team can coach me better to help you! 😀.
        /// </summary>
        public static string ShareAppFeedbackCarouselContent {
            get {
                return ResourceManager.GetString("ShareAppFeedbackCarouselContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app feedback.
        /// </summary>
        public static string ShareAppFeedbackCarouselTitle {
            get {
                return ResourceManager.GetString("ShareAppFeedbackCarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please share your thoughts.....
        /// </summary>
        public static string ShareAppFeedbackInputPlaceholder {
            get {
                return ResourceManager.GetString("ShareAppFeedbackInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitFeedbackButtonText {
            get {
                return ResourceManager.GetString("SubmitFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a team tour.
        /// </summary>
        public static string TakeATeamTourButtonText {
            get {
                return ResourceManager.GetString("TakeATeamTourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to know more about what goes on, click on the button that reads *Take a tour*.
        /// </summary>
        public static string TeamTourIntroText {
            get {
                return ResourceManager.GetString("TeamTourIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to know more about the bulleted items that have been mentioned, make sure to click on the button that reads _Take a tour_.
        /// </summary>
        public static string TourIntroText {
            get {
                return ResourceManager.GetString("TourIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns out there is something that my tiny 🤖 🧠 just cannot figure out!.
        /// </summary>
        public static string UnrecognizedInputCardContentPart1 {
            get {
                return ResourceManager.GetString("UnrecognizedInputCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, it may just be that you as the end user may not *have the right idea* about what I do. Click on the *Welcome Message* button to find out what I do.
        /// </summary>
        public static string UnrecognizedInputCardContentPart2 {
            get {
                return ResourceManager.GetString("UnrecognizedInputCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh Oh!.
        /// </summary>
        public static string UnrecognizedInputCardTitleText {
            get {
                return ResourceManager.GetString("UnrecognizedInputCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string UnrecognizedInputTakeATour {
            get {
                return ResourceManager.GetString("UnrecognizedInputTakeATour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Article.
        /// </summary>
        public static string ViewFullArticleButtonText {
            get {
                return ResourceManager.GetString("ViewFullArticleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Related Articles.
        /// </summary>
        public static string ViewRelatedArticlesButtonText {
            get {
                return ResourceManager.GetString("ViewRelatedArticlesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Benefits.
        /// </summary>
        public static string WelcomeCardBulletListItem1 {
            get {
                return ResourceManager.GetString("WelcomeCardBulletListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Leave.
        /// </summary>
        public static string WelcomeCardBulletListItem2 {
            get {
                return ResourceManager.GetString("WelcomeCardBulletListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Travel.
        /// </summary>
        public static string WelcomeCardBulletListItem3 {
            get {
                return ResourceManager.GetString("WelcomeCardBulletListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are reading this, it is because you are wondering about what I do. I am {0}, a simple bot that will query against a knowledge base and return you an answer..
        /// </summary>
        public static string WelcomeCardContentPart1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask me about many topics such as:.
        /// </summary>
        public static string WelcomeCardContentPart2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If I am unable to help you with a question, I will connect you with an expert..
        /// </summary>
        public static string WelcomeCardContentPart3 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string WelcomeCardTitleText {
            get {
                return ResourceManager.GetString("WelcomeCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! I am {0} If you are reading this, it is because I have been installed to this team - *{1}* where you can do two things. Either you can: self assign a case to handle, or chat with a questioner. You are the subject matter experts (or SMEs) - and my job is to help you help the user! 😀.
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        public static string WelcomeTeamCardTitleText {
            get {
                return ResourceManager.GetString("WelcomeTeamCardTitleText", resourceCulture);
            }
        }
    }
}
